<?php

/**
 * @file
 * Implementation of some citeproc alters.
 */

/**
 * Implements citeproc_convert_mods_to_citeproc_jsons_alter
 *
 * @param $output
 * @param $mods
 */
function upei_roblib_citeproc_convert_mods_to_citeproc_jsons_alter(&$output, $mods) {
  module_load_include('inc', 'citeproc', 'includes/converter');
  $type = $output['type'] = upei_roblib_citeproc_local_to_csl_type($mods);
  $parented = "'$type'='book' or '$type'='chapter' or '$type'='article-journal'";
  if ($output['publisher'] == NULL) {
    $output['publisher'] = convert_mods_to_citeproc_json_query($mods, '/mods:mods/mods:originInfo/mods:publisher |
     /mods:mods/mods:relatedItem[@type="host"]/mods:originInfo/mods:publisher');
  }
  if ($output['publisher-place'] == NULL) {
    $output['publisher-place'] = convert_mods_to_citeproc_json_query($mods, '(/mods:mods/mods:originInfo/mods:place/mods:placeTerm[@type="text"] | /mods:mods/mods:relatedItem[@type="host"]/mods:originInfo/mods:place/mods:placeTerm[@type="text"])[1]');
  }
  if($output['collection-title'] == NULL){
    $output['collection-title'] = convert_mods_to_citeproc_json_query($mods, "/mods:mods/mods:relatedItem[@type='series']/mods:titleInfo/mods:title |
            /mods:mods[not($parented)]/mods:relatedItem[@type='host']/mods:titleInfo/mods:title");
  }
  if($output['number-pmid'] == NULL) {
    $output['number-pmd'] = convert_mods_to_citeproc_json_query($mods, '/mods:mods/mods:identifier[@type="pmid"] | /mods:mods/mods:identifier[@type="accession"]');
  }
  if($output['number-pmid'] == NULL) {
    $output['number-pmcid'] = convert_mods_to_citeproc_json_query($mods, '/mods:mods/mods:identifier[@type="pmcid"] | /mods:mods/mods:identifier[@type="pmc"]');
  }
  if($output['number-pmid'] == NULL) {
    $output['number-nihmsid'] = convert_mods_to_citeproc_json_query($mods, '/mods:mods/mods:identifier[@type="nihmsid"] | /mods:mods/mods:identifier[@type="mid"]');
  }
}

function upei_roblib_citeproc_local_to_csl_type($mods) {
  $genre = $mods->xpath("//mods:mods[1]/mods:genre");

  if(empty($genre)){
    return convert_mods_to_citeproc_json_type($mods);
  }
  $term = strtolower(trim((string)$genre[0]));
  switch ($term) {
    case 'journal article':
    case 'journal, electronic':
    case 'newspaper article':
    case 'magazine article':
    case '':
      return 'article-journal';
    case 'book chapter':
    case 'book section':
    case 'book, section':
      return 'chapter';
    case 'book, whole':
      return 'book';
    case 'conference proceedings':
      return 'paper-conference';
    case 'dissertation/thesis':
    case 'signature project':
      return 'thesis';
    case 'web page':
      return 'webpage';
    default:
      return convert_mods_to_citeproc_json_type($mods);
  }
}

